# Generated by Django 6.0.4 on 2026-09-07 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_alter_product_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='min_order_quantity_override',
            field=models.PositiveIntegerField(blank=True, help_text='Остави празно, за да важи минимумът на категорията.', null=True, verbose_name='минимална поръчка (бр.)'),
        ),
    ]
