# Generated by Django 6.0.4 on 2026-09-06 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0002_alter_category_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='min_order_quantity',
            field=models.PositiveIntegerField(default=1, help_text='Най-малкият брой, който клиентът може да поръча от продукт в тази категория.', verbose_name='минимална поръчка (бр.)'),
        ),
    ]
