# Generated by Django 6.0.4 on 2026-09-07 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_category_min_order_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='sold_individually',
            field=models.BooleanField(default=False, help_text='Отметни за твърд алкохол. Тогава бутоните + и - в количката променят количеството с 1 бр. Иначе стъпката е равна на минималната поръчка.', verbose_name='продава се поединично'),
        ),
    ]
